import type { AnimeData } from "@/types/RecentCard";

export const sampleAnimeData1: AnimeData[] = [
  {
    id: 1,
    malURL: "https://myanimelist.net/anime/1",
    title: "Cowboy Bebop",
    type: "TV",
    source: "Original",
    episodes: 26,
    status: "Finished Airing",
    rating: "R - 17+",
    score: 8.8,
    scoredBy: 950000,
    rank: 42,
    synopsis:
      "In the year 2071, a group of bounty hunters chase criminals across the solar system.",
    season: "Spring",
    year: 1998,
    producers: ["Bandai Visual", "Sunrise"],
    genres: ["Action", "Sci-Fi"],
    themes: ["Space", "Bounty Hunters"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/4/19644t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/4/19644l.jpg",
    },
  },
  {
    id: 2,
    malURL: "https://myanimelist.net/anime/5114",
    title: "Fullmetal Alchemist: Brotherhood",
    type: "TV",
    source: "Manga",
    episodes: 64,
    status: "Finished Airing",
    rating: "R - 17+",
    score: 9.1,
    scoredBy: 1900000,
    rank: 1,
    synopsis:
      "Two brothers search for a Philosopher's Stone after attempting the forbidden act of human transmutation.",
    season: "Spring",
    year: 2009,
    producers: ["Aniplex", "Square Enix", "Bones"],
    genres: ["Action", "Adventure", "Drama"],
    themes: ["Military", "Alchemy"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/1223/96541t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/1223/96541l.jpg",
    },
  },
  {
    id: 3,
    malURL: "https://myanimelist.net/anime/30276",
    title: "One Punch Man",
    type: "TV",
    source: "Web Manga",
    episodes: 12,
    status: "Finished Airing",
    rating: "R - 17+",
    score: 8.5,
    scoredBy: 1500000,
    rank: 120,
    synopsis:
      "Saitama, a superhero who can defeat any opponent with a single punch, seeks meaning in his life.",
    season: "Fall",
    year: 2015,
    producers: ["TV Tokyo", "Bandai Visual"],
    genres: ["Action", "Comedy"],
    themes: ["Super Power", "Parody"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/12/76049t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/12/76049l.jpg",
    },
  },
  {
    id: 4,
    malURL: "https://myanimelist.net/anime/31240",
    title: "Re:Zero kara Hajimeru Isekai Seikatsu",
    type: "TV",
    source: "Light Novel",
    episodes: 25,
    status: "Finished Airing",
    rating: "R - 17+",
    score: 8.3,
    scoredBy: 1700000,
    rank: 160,
    synopsis:
      "Subaru Natsuki is transported to a fantasy world and discovers he has the ability to return from death.",
    season: "Spring",
    year: 2016,
    producers: ["Media Factory", "Kadokawa"],
    genres: ["Drama", "Fantasy", "Thriller"],
    themes: ["Isekai", "Time Travel"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/11/79410t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/11/79410l.jpg",
    },
  },
];

export const sampleAnimeDataSet2: AnimeData[] = [
  {
    id: 5,
    malURL: "https://myanimelist.net/anime/11061",
    title: "Hunter x Hunter (2011)",
    type: "TV",
    source: "Manga",
    episodes: 148,
    status: "Finished Airing",
    rating: "PG-13",
    score: 9.0,
    scoredBy: 1600000,
    rank: 4,
    synopsis: "Gon Freecss sets out to become a Hunter and find his father.",
    season: "Fall",
    year: 2011,
    producers: ["VAP", "Nippon Television Network"],
    genres: ["Action", "Adventure", "Fantasy"],
    themes: ["Shounen"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/1337/99013t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/1337/99013l.jpg",
    },
  },
  {
    id: 6,
    malURL: "https://myanimelist.net/anime/9253",
    title: "Steins;Gate",
    type: "TV",
    source: "Visual Novel",
    episodes: 24,
    status: "Finished Airing",
    rating: "PG-13",
    score: 9.1,
    scoredBy: 1400000,
    rank: 2,
    synopsis:
      "A self-proclaimed mad scientist discovers a way to send messages to the past, altering the future.",
    season: "Spring",
    year: 2011,
    producers: ["Frontier Works", "White Fox"],
    genres: ["Drama", "Sci-Fi", "Thriller"],
    themes: ["Time Travel", "Psychological"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/5/73199t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/5/73199l.jpg",
    },
  },
  {
    id: 7,
    malURL: "https://myanimelist.net/anime/28977",
    title: "Gintama°",
    type: "TV",
    source: "Manga",
    episodes: 51,
    status: "Finished Airing",
    rating: "R - 17+",
    score: 9.0,
    scoredBy: 450000,
    rank: 7,
    synopsis:
      "The eccentric samurai Gintoki and his friends continue their bizarre adventures in a sci-fi Edo.",
    season: "Spring",
    year: 2015,
    producers: ["TV Tokyo", "Aniplex"],
    genres: ["Action", "Comedy"],
    themes: ["Samurai", "Parody"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/3/72078t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/3/72078l.jpg",
    },
  },
  {
    id: 8,
    malURL: "https://myanimelist.net/anime/19815",
    title: "No Game No Life",
    type: "TV",
    source: "Light Novel",
    episodes: 12,
    status: "Finished Airing",
    rating: "PG-13",
    score: 8.1,
    scoredBy: 1200000,
    rank: 300,
    synopsis:
      "Siblings Sora and Shiro are transported to a world where everything is decided by games.",
    season: "Spring",
    year: 2014,
    producers: ["Media Factory"],
    genres: ["Fantasy", "Comedy"],
    themes: ["Game", "Isekai"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/5/65187t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/5/65187l.jpg",
    },
  },
];

export const sampleAnimeDataSet3: AnimeData[] = [
  {
    id: 9,
    malURL: "https://myanimelist.net/anime/38408",
    title: "Kimetsu no Yaiba ",
    type: "TV",
    source: "Manga",
    episodes: 26,
    status: "Finished Airing",
    rating: "R - 17+",
    score: 8.6,
    scoredBy: 1800000,
    rank: 85,
    synopsis:
      "After his family is slaughtered by demons, Tanjiro Kamado joins the Demon Slayer Corps.",
    season: "Spring",
    year: 2019,
    producers: ["Aniplex", "Shueisha"],
    genres: ["Action", "Supernatural"],
    themes: ["Historical", "Demons"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/1286/99889t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
    },
  },
  {
    id: 10,
    malURL: "https://myanimelist.net/anime/21",
    title: "One Piece",
    type: "TV",
    source: "Manga",
    episodes: null,
    status: "Currently Airing",
    rating: "PG-13",
    score: 8.7,
    scoredBy: 2000000,
    rank: 70,
    synopsis: "Monkey D. Luffy sails the Grand Line to become the Pirate King.",
    season: "Fall",
    year: 1999,
    producers: ["Toei Animation"],
    genres: ["Action", "Adventure", "Fantasy"],
    themes: ["Pirates", "Shounen"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/6/73245t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/6/73245l.jpg",
    },
  },
  {
    id: 11,
    malURL: "https://myanimelist.net/anime/38000",
    title: "Vinland Saga",
    type: "TV",
    source: "Manga",
    episodes: 24,
    status: "Finished Airing",
    rating: "R - 17+",
    score: 8.7,
    scoredBy: 600000,
    rank: 70,
    synopsis:
      "Thorfinn seeks revenge against the man who killed his father in a tale of Viking conquest.",
    season: "Summer",
    year: 2019,
    producers: ["Kodansha", "Twin Engine"],
    genres: ["Action", "Adventure", "Drama"],
    themes: ["Historical", "Seinen"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/1500/103005t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/1500/103005l.jpg",
    },
  },
  {
    id: 12,
    malURL: "https://myanimelist.net/anime/41084",
    title: "Jujutsu Kaisen",
    type: "TV",
    source: "Manga",
    episodes: 24,
    status: "Finished Airing",
    rating: "R - 17+",
    score: 8.8,
    scoredBy: 1700000,
    rank: 40,
    synopsis:
      "Yuji Itadori joins a secret organization to fight curses after swallowing a powerful cursed object.",
    season: "Fall",
    year: 2020,
    producers: ["MAPPA"],
    genres: ["Action", "Supernatural"],
    themes: ["School", "Combat"],
    images: {
      smallImgUrl: "https://cdn.myanimelist.net/images/anime/1171/109222t.jpg",
      largeImgUrl: "https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
    },
  },
];
